[tool.poetry]
name = "back-dj-python"
version = "0.1.0"
description = ""
authors = ["gustavokubiack <guukubiack@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django-cors-headers = "^3.13.0"
djangorestframework = "^3.14.0"
djangorestframework-simplejwt = "^5.2.0"
Django = "^4.1.1"
Pillow = "^9.2.0"
python-magic-bin = "0.4.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
